name: sabatex.V1C8.ComponentModel.DataAnnotations
on:
  push:
    branches:
      - master
    paths:
      - 'src/sabatex.V1C8.ComponentModel.DataAnnotations/sabatex.V1C8.ComponentModel.DataAnnotations.csproj'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 5.0.100
      
       # Publish V1C8
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: 'src/sabatex.V1C8.ComponentModel.DataAnnotations/sabatex.V1C8.ComponentModel.DataAnnotations.csproj'
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
